const names = {
  0: "blank",
  1: "init-to-right",
  2: "init-to-left",
  3: "init-to-top",
  4: "init-to-bottom",
  5: "init-to-d-top-left",
  6: "init-to-d-top-right",
  7: "init-to-d-bottom-left",
  8: "init-to-d-bottom-right",
  9: "vertical",
  10: "diagonally",
  11: "horizontal",
  12: "capital-t",
  13: "top-left",
  14: "bottom-left",
  15: "top-right",
  16: "bottom-right",
  17: "d-left-top",
  18: "d-left-bottom",
  19: "d-right-top",
  20: "d-right-bottom",
  21: "end-to-right",
  22: "end-to-left",
  23: "end-to-top",
  24: "end-to-bottom",
  25: "end-to-d-top-left",
  26: "end-to-d-top-right",
  27: "end-to-d-bottom-left",
  28: "end-to-d-bottom-right",
};

export default names;
